trigger:
- main

pool:
  vmImage: 'windows-2019'

variables:
  BuildConfiguration: 'Release'

steps:
# Step 1: Find the WebApp.csproj and restore dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore WebApp.csproj Dependencies'
  inputs:
    command: 'restore'
    projects: '**/WebApp.csproj'

# Step 2: Build WebApp.csproj
- task: DotNetCoreCLI@2
  displayName: 'Build WebApp.csproj'
  inputs:
    command: 'build'
    projects: '**/WebApp.csproj'
    arguments: '--configuration $(BuildConfiguration)'

# Step 3: Publish WebApp.csproj
- task: DotNetCoreCLI@2
  displayName: 'Publish WebApp.csproj'
  inputs:
    command: 'publish'
    projects: '**/WebApp.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# Step 4: Zip the Published Files
- task: ArchiveFiles@2
  displayName: 'Zip Published WebApp Files'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'

# Step 5: Publish the Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/drop.zip'
    artifactName: 'drop'
    publishLocation: 'Container'
