trigger:
- main  # Adjust as per your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'  # Ensures the latest patch version of .NET 6
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet build WebApp/WebApp.csproj --configuration Release
  displayName: 'Build WebApp'

- script: dotnet test WebApp.UnitTest/WebApp.UnitTest.csproj --configuration Release
  displayName: 'Run Unit Tests'
