trigger:
- main  # Runs when code is pushed to 'main'

pool:
  vmImage: 'windows-2022'  # Uses Windows agent

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '6.0.x'
  artifactName: 'drop'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '**/*.sln'  

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '**/*.sln'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Run Tests'
  inputs:
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: 'Publish Application'
#   inputs:
#     command: 'publish'
#     publishWebProjects: true
#     arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#     zipAfterPublish: true

# - task: PublishBuildArtifacts@1
#   displayName: 'Save Build Artifacts'
#   inputs:
#     pathToPublish: '$(Build.ArtifactStagingDirectory)'
#     artifactName: '$(artifactName)'

